Add menu item for opening settings
romainguy/kotlin-explorer pull request #17
Opened 2024-04-10 22:18 UTC by EpicDima

2024-04-15 21:54 UTC, romainguy requested changes

2024-04-15 21:54 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/KotlinExplorer.kt
> +                        val result = SearchEngine.find(activeTextArea, e.searchContext)
Your PR shouldn't change formatting anywhere not needed

2024-04-18 11:28 UTC, EpicDima commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/KotlinExplorer.kt
> +                        val result = SearchEngine.find(activeTextArea, e.searchContext)
Sorry, ok

2024-04-19 10:38 UTC, romainguy approved these changes
Thanks!

2024-04-19 10:38 UTC, merged