Add Line Numbers to Dex Dump
romainguy/kotlin-explorer pull request #19
Opened 2024-05-01 19:58 UTC by alonalbert

I rewrote the DexDump parsing into a dedicated class.

I changed the implementation to be (IMO) less brittle and more readable.

2024-05-01 21:40 UTC, romainguy requested changes
Thanks, I left a couple of comments. A few more things:

- There are now 2 empty lines between methods in the output instead of just 1. I remember I had to do something to deal with this in the original implementation as well.
- There seems to be a bug with naming classes. For instance I got this in a dump: `class IntOffset..ExternalSyntheticBackport0` (note the two dots)
- Could you add a menu to turn debug line numbers on/off? It would make it more obvious to users what those numbers are, but more importantly it would make copy/pasting out of the tool easier when line numbers are disabled.
- Your change breaks another feature: when clicking on a line with a jump (goto/if/etc.) in the DEX output, the tool will draw a line to show where the jump will go. If the target line has a debug line number in the output, the feature stops working (prob. because the regex I use assumes whitespace at the beginning; one of the reasons why I wanted to change the parsers to output a list of class/methods/instructions)

2024-05-01 21:40 UTC, romainguy commented on build.gradle.kts
> +                runtimeOnly("org.jetbrains.skiko:skiko-awt-runtime-macos-arm64:${extra["skiko.version"] as String}")
This breaks on macOS, the native library can't be found if it's not `implementation()` :/

2024-05-01 21:40 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/dex/DexDumpParser.kt
> +private const val CLASS_START = "Class #"
I've been following the `SnakeCase` style for constants here.

2024-05-01 21:40 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/dex/DexDumpParser.kt
> +            .filter { it.methods.isNotEmpty() }
You can combine those two filters in a single one

2024-05-01 21:40 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/dex/DexDumpParser.kt
> +                val prefix = when (lineNumber != null) {
Use an if/else here instead of when/true/false

2024-05-02 14:50 UTC, alonalbert commented on build.gradle.kts
> +                runtimeOnly("org.jetbrains.skiko:skiko-awt-runtime-macos-arm64:${extra["skiko.version"] as String}")
Done

2024-05-02 14:55 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/dex/DexDumpParser.kt
> +private const val CLASS_START = "Class #"
Done

2024-05-02 14:56 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/dex/DexDumpParser.kt
> +            .filter { it.methods.isNotEmpty() }
Done

2024-05-02 16:47 UTC, romainguy commented
Thanks for the updates! One last issue, there are still 2 empty lines between methods in the dump instead of 1.

2024-05-02 17:11 UTC, romainguy approved these changes
Awesome, thank you!

2024-05-02 17:12 UTC, merged