Add ByteCode Support
romainguy/kotlin-explorer pull request #29
Opened 2024-05-03 19:21 UTC by alonalbert

Line number data is included in the output but embedded into the code yet.

2024-05-03 19:30 UTC, romainguy requested changes

2024-05-03 19:30 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/CodeTextArea.kt
> +                -1 -> 0 to srcLine - 1
There's a drawback with this approach: you always start from 0 for backward jumps which means we may need to scan the entire text area. Jumps tend to be close to the source instruction so it makes more sense to do what the original code did and start from the source line and walk towards the destination. I also think your solution might introduce a bug in the DEX output: the addresses are local to a function, so you could cause a backward jump to jump to a previously defined function since you start from line 0.

2024-05-03 19:30 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/bytecode/ByteCodeTextArea.kt
> +fun main() {
Remove?

2024-05-06 23:43 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/CodeTextArea.kt
> +                -1 -> 0 to srcLine - 1
Rewrote this with the new` Code` model

2024-05-06 23:53 UTC, romainguy approved these changes

2024-05-06 23:53 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +        val javap = process(
Optimization note: we should do this only when showing the bytecode panel to speed up the process (and similarly not decompile the dex if we're not showing the dex bytecode). Or alternatively we could do this in parallel with dex decompilation (and the oat dump could happen in parallel with the dex dump).

2024-05-06 23:54 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +        val javap = process(
(this can be done later btw)

2024-05-07 03:14 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +        val javap = process(
Yeah, I like parallel compilation better because that way, the code will be available immediately when you add a hidden view

2024-05-07 13:57 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +        val javap = process(
As you suggested, I'll do in another cl

2024-05-07 15:44 UTC, merged