Add a Code Model
romainguy/kotlin-explorer pull request #30
Opened 2024-05-04 21:16 UTC by alonalbert

This makes it easier to detect jumps and toggle show-line-number

2024-05-05 02:31 UTC, romainguy requested changes
Thanks! In addition to the comments I left, I noticed a huge difference in code formatting:
- Without line numbers the indentation is now 2 spaces, please keep the original, it's much more readable to me
- With line numbers on, the indentation is very wide (12 spaces??) with a lot of empty space around the line numbers. See screenshot
<img width="449" alt="Screenshot 2024-05-04 at 7 31 29 PM" src="https://github.com/romainguy/kotlin-explorer/assets/869684/ebb20dec-d4e3-430e-afe1-f9cc556103db">

2024-05-05 02:31 UTC, romainguy commented on build.gradle.kts
> +                implementation("com.google.guava:guava:${extra["guava"]}")
Do you really need this dependency for just `PeekingIterator` (whatever that does)? That seems overkill.

2024-05-05 02:31 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/code/CodeTextArea.kt
> +    private var presentationMode: Boolean = false,
Why not make these public properties with a custom setter instead of creating `setXXX()` functions down below?

2024-05-05 02:31 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/code/CodeTextArea.kt
> +    fun setContent(content: CodeContent) {
Use properties

2024-05-05 02:31 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/code/CodeTextArea.kt
> +            val x2 = bounds2.x.toInt() - 2
Why did you remove all that logic? When no line numbers are present it's nice to have tighter arrows as they don't need to go all the way to the left

2024-05-05 02:31 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/oat/OatDumpParser.kt
> +import com.google.common.collect.PeekingIterator
See my comment earlier, I'd really prefer if we didn't bring Guava along

2024-05-05 03:34 UTC, alonalbert commented on build.gradle.kts
> +                implementation("com.google.guava:guava:${extra["guava"]}")
`PeekingIterator` allows peeking the current value without consuming it which is very useful for parsing.

I should be possible to fork it do you really want to?
What's the issue with dependencies? It's not like this needs to run on a smartwatch or something :)

2024-05-05 03:41 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/code/CodeTextArea.kt
> +    private var presentationMode: Boolean = false,
TBH, I'm not a fan of setters that do non trivial work. But OK.

2024-05-05 03:47 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/code/CodeTextArea.kt
> +    fun setContent(content: CodeContent) {
I thing this would be awkward. Notice there is no backing field for a Content. Setting content updates 2 fields, `text`, and `code`.

2024-05-05 03:49 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/code/CodeTextArea.kt
> +            val x2 = bounds2.x.toInt() - 2
The logic was broken and I didn't really understand what you were doing.

![image](https://github.com/romainguy/kotlin-explorer/assets/1660304/8e00db93-32e3-444c-a53d-a37ec4158389)


How about you fix it after?

2024-05-05 03:51 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/oat/OatDumpParser.kt
> +import com.google.common.collect.PeekingIterator
Let me know if you want to fork the iterator

2024-05-05 14:56 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/code/CodeTextArea.kt
> +            val x2 = bounds2.x.toInt() - 2
I changed things a bit. The code model now supports `indent` and a `LineNumberMode` that make things easier.

I restored this code and tweaked the values. I used constants but it should really use the `indent` and `FixedWidth.width` vales.

I don't 100% understand the code so I kept it with constants. I'll fix later or you can do it if you ant. I suspect the code can be simplified now.

![image](https://github.com/romainguy/kotlin-explorer/assets/1660304/b7e4ccd8-8582-4b5c-a2e9-104dc14bb67e)


![image](https://github.com/romainguy/kotlin-explorer/assets/1660304/5da02c25-8635-484c-8d5a-fabc90f80480)

2024-05-05 14:57 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/code/CodeTextArea.kt
> +    fun setContent(content: CodeContent) {
I changed things a bit so Done.

2024-05-05 15:27 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/oat/OatDumpParser.kt
> +import com.google.common.collect.PeekingIterator
I forked and simplified PeekingIterator.

2024-05-05 15:27 UTC, alonalbert commented on build.gradle.kts
> +                implementation("com.google.guava:guava:${extra["guava"]}")
Done

2024-05-05 20:35 UTC, alonalbert commented
FYI, the OAT parser has a bug in ti. Infinte loop sometimes
I'm investigating

2024-05-05 20:50 UTC, alonalbert commented
OK, fixed it.

2024-05-06 16:10 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/code/CodeTextArea.kt
> +            val x2 = bounds2.x.toInt() - 2
Awesome, thank you! The breakage you saw was because I was assuming at least 4 spaces, but it should be easy to fix based on an indent setting.

2024-05-06 16:12 UTC, romainguy commented
> Note that we have to account for long line numbers so

That's what I thought. Have you tried eating up into the left indent instead? I don't know how pretty it would look but something like this:

```
class Foo
    <init>()V // Foo.<init>()
1:      0000: invoke-direct {v0}, Ljava/lang/Object;.<init>:()V // method@0008
        0003: return-void
    <bar>()V // Foo.<init>()
1000:   0000: invoke-direct {v0}, Ljava/lang/Object;.<init>:()V // method@0008
        0003: return-void
```

2024-05-06 16:16 UTC, romainguy approved these changes

2024-05-06 16:42 UTC, merged