Add a Progress Indicator
romainguy/kotlin-explorer pull request #31
Opened 2024-05-05 02:27 UTC by alonalbert

I tried to add a popup dialog with a progress bar but I couldn't get the dialog to show. I added it to the status bar instead.

2024-05-05 02:39 UTC, romainguy requested changes

2024-05-05 02:39 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +            )
Keep the ) at the end of the previous line or fix the indent

2024-05-05 02:39 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/KotlinExplorer.kt
> +                val width = 160.dp
Instead of hardcoding the width, just move the progress bar all the way to the right (just add a `Space` with a modifier with a weight set to 1 between `Text` and `LinearProgressIndicator`)

2024-05-05 02:39 UTC, romainguy commented
Looks nice with the progress bar!

2024-05-05 03:23 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +            )
Done

2024-05-05 03:24 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/KotlinExplorer.kt
> +                val width = 160.dp
I initially had the bar on the far right and I didn't like it. The bar is too far away from the progress.

I think it's nice when they are near each other.

2024-05-05 03:26 UTC, alonalbert commented
Any idea how to add a dialog?

When I render a Dialog, nothing is displayed and the UI looks like some effect was done to it to reflect that it's behind something.

2024-05-06 03:33 UTC, romainguy approved these changes

2024-05-06 03:33 UTC, romainguy approved these changes

2024-05-06 15:48 UTC, romainguy commented
I'm resolving the conflicts. The Gradle cleanup removed too much.

2024-05-06 15:56 UTC, romainguy commented
See https://github.com/romainguy/kotlin-explorer/pull/35

2024-05-06 15:56 UTC, closed without merging