Launch Some Task in Parallel to Speed Things Up
romainguy/kotlin-explorer pull request #42
Opened 2024-05-08 01:28 UTC by alonalbert

`javap` and `dexdump` can be launched in the background while we continue processing.

I changed the semantics of Status to show what has already been done, rather that's being done now. This is because now, things can happen at the same time. For example:

`Creating Java ByteCode` & `Creating Dex Dump` would be set at almost the same time and we wouldn't see one of them.

I'm using an `AtomicFloat` to guard the step counter and I changed some of the `launch(ui)` to `withContext(ui)` where it wasn't blocking further processing.

Note that now, if javap or dexdump fails, we keep going so we don't set the progress to Done. I extracted the `onStatusUpdate()` for success and failure to a single call so we can easily see how many times we call getAndIncrement

2024-05-08 03:31 UTC, romainguy requested changes

2024-05-08 03:31 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +private class AtomicFloat(value: Float) : AtomicReference<Float>(value) {
Why not use an AtomicInteger or Kotlin’s AtomicInt? The step is an integer, not a float. The float division is done on status update. Just do a toFloat() after getAndIncrement.

2024-05-08 03:31 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +import androidx.lifecycle.AtomicReference
See comment below, also we should probably use Kotlin’s atomic primitives instead.

2024-05-08 03:57 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +private class AtomicFloat(value: Float) : AtomicReference<Float>(value) {
I wanted to avoid chaining the `toFloat()` everywhere. Just a convenience thing.

How about this one? I defined an `infix` function `over`, as in:

```
   1 over 5 == 0.5f
```

2024-05-08 03:58 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +import androidx.lifecycle.AtomicReference
yeah, that got auto imported accidentally.

2024-05-08 12:52 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +private class AtomicFloat(value: Float) : AtomicReference<Float>(value) {
Actually, I have a better idea on how to do this more cleanly. Will update later this morning

2024-05-08 21:45 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +private class AtomicFloat(value: Float) : AtomicReference<Float>(value) {
OK, PTAL.

2024-05-08 23:10 UTC, romainguy requested changes

2024-05-08 23:10 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +                withContext(ui) {
Why did you replace the launches with withContext?

2024-05-08 23:10 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +    0 until 1
Remove?

2024-05-09 00:36 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +                withContext(ui) {
I replace ones that don't block work. For example, if kotlinc fails, we can't proceed anyway. 

Did I miss something?

2024-05-09 00:38 UTC, alonalbert commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/Disassembly.kt
> +    0 until 1
Done

2024-05-09 19:35 UTC, romainguy approved these changes

2024-05-09 19:35 UTC, merged