Initial support for Windows
romainguy/kotlin-explorer pull request #7
Opened 2024-02-07 08:07 UTC by Omico

2024-02-07 08:38 UTC, Omico commented
Just notice we can use `org.jetbrains.jewel.window.utils.DesktopPlatform` to check what platform users use. Do I need to migrate to that?

2024-02-07 08:48 UTC, Omico commented
Seems `org.jetbrains.jewel.window.TitleBar` doesn't work correctly on Windows. 

![image](https://github.com/romainguy/kotlin-explorer/assets/14316223/0c07a71f-8cc1-46b2-a70b-670e6a21a7a6)

If we remove it, everything looks fine.

![image](https://github.com/romainguy/kotlin-explorer/assets/14316223/813428e2-bfb2-4981-a3b7-80bf652c4b5c)

2024-02-08 01:42 UTC, romainguy requested changes

2024-02-08 01:42 UTC, romainguy commented on src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/OS.kt
> +package dev.romainguy.kotlin.explorer
Add missing copyright header please, otherwise looks good, thanks!

2024-02-08 02:38 UTC, Omico commented
Do you want me to add Spotless to do that automatically in another PR?

2024-02-08 02:39 UTC, romainguy commented
Thanks for the suggestion but I'm not fond of auto formatters :)

Thanks for the PR. I'll try to keep Windows in mind but I won't be able to regularly test future changes :/

2024-02-08 02:39 UTC, merged