Enable strong skipping mode and mark stable classes
romainguy/kotlin-explorer pull request #70
Opened 2024-09-04 08:35 UTC by Goooler

Strong skipping mode is the default from Kotlin 2.0.20.

https://github.com/JetBrains/kotlin/releases/tag/v2.0.20

2024-09-05 18:07 UTC, romainguy requested changes

2024-09-05 18:07 UTC, romainguy commented on build.gradle.kts
> +    reportsDestination = layout.buildDirectory.dir("compose_compiler")
Small nitpicks, please use - instead of _ for consistency with other files/folders.

2024-09-05 18:07 UTC, romainguy commented on build.gradle.kts
> +    stabilityConfigurationFile = layout.projectDirectory.file("stability_config.conf")
Name the file compose-stability.config

2024-09-05 23:23 UTC, Goooler commented on build.gradle.kts
> +    stabilityConfigurationFile = layout.projectDirectory.file("stability_config.conf")
0edfc3138d90bd41ad536b60f1191bc3e2e1afab

2024-09-05 23:25 UTC, romainguy requested changes

2024-09-05 23:25 UTC, romainguy commented on build.gradle.kts
> +    reportsDestination = layout.buildDirectory.dir("compose_compiler")
Could you use `compose-compiler` instead of `compose_compiler`? Thanks!

2024-09-05 23:26 UTC, Goooler commented on build.gradle.kts
> +    reportsDestination = layout.buildDirectory.dir("compose_compiler")
88e8db5077eb2cc236f332ebbc12937b3fad6a8c

2024-09-06 00:45 UTC, romainguy approved these changes
Thank you!

2024-09-06 00:46 UTC, merged